### ISSUE TITLE
NoMethodError: undefined method `match' for nil:NilClass

### ISSUE THREAD

**Issue by lucascaton** [fritz0705/ruby-wunderlist#3]
Running:

``` ruby
require "wunderlist"
api = Wunderlist::API.new
api.login "my_email@email.com", "my_password"
```

I got this error:

```
NoMethodError: undefined method `match' for nil:NilClass
```

---
- Ruby 2.0.0p353
- ruby-wunderlist 0.4

**Comment by fritz0705** [comment]
This happens because this Gem was developed for a very early version of Wunderlist (February 2012), and I'm no longer maintaining this Gem. If you want to change this, feel free to fork this repository and do the appropriate refactoring.

**Comment by lucascaton** [comment]
Ok! :+1: 

Thanks anyway...
